language: python
python: 3.6
before_install:
- sudo apt-get install texlive
install:
- pip install numpy matplotlib scipy scikit-learn pytest coveralls sphinx sphinx-gallery
script:
- sphinx-build doc out
- pdflatex -output-directory=out doc/math.tex
- coverage run --source=skpp -m pytest -s
after_success:
- coveralls
notifications:
  email:
  - pvlkmrv@gmail.com
deploy:
- provider: pages
  skip-cleanup: true
  github-token:
    secure: "BZTdSvHWdz2tdZ1iL67nh5g+3PgFPjZGiVRR5yrgqS7hwX+Ds/wh/0gPu0zEqWIQjeDmPGtDEykYU+NKxkJsIIxkh3BNkWQu1DWdyH9Te9IJcH2QlmiC86qkfAZfoJu/PgvhfEVXZEFLhYDROypy7B4ADb/PURVCNiARYZhGv+a1oU/XRWHWw82H69CIFeYLhN5ucyX/4tjjiQ3Mo/D2f0K1Bk92/KjVRZRrjb4WjPH4IEiqGqOUNnsC+8dQerGjzXp2qWxmK8NpoxUqqaCybP56XNzLOKEjMuyUMZ5lBuIxduDGwPP35JNbGzq/ucI0cE79tLPsxESqWNZJAeEFAWyQjZgHQO2vp7n1nM7t3uyZCRRwImEFBpMQtWj/wPzZWNgJHpgEX5AejhUWBJC+hhK1hW4JqDCWMwCICbolnICy/DvwLPJUcpmwc9L+S4wKhDYm+kK2vl4srx9PLCWTzIHVd3nW/rX4QcUBwx8w+jEmzdpL5qiYKe1aV2ZWwWgaH1bslLUOwEoXkoehadnxJsaiPuIw4oQRA0xR5cR1Tm7y0yuqkO9LpVIYSTJGFD23ZOgfT5qwW3TYWXf3ZdjVdzk3v0lbDcvVPyupRIU6P4BYQK3SvLmVVWPwvOuilGiACx1mHkriBOI23L0sc3m80rPYqGo8ZOnRyUWfuQJRcd4="
  local-dir: out
  on:
    branch: master
- provider: pypi
  user: pavelkomarov
  password:
    secure: L12e2JIGYwgiK+0s1pp2A/OsdZmRQALXbMTEjOWTNurWhTxXZZJ9R+M6U2M9ZmkxZ6we3maZ3Bcuv10zzvi/LoE0VIgaaL+kLHYkq1hPe83wxdmEepk4/uzIABy6XKunx59ennMJSaMZM+9Ks5VzZ1GuVhKhpt13FQQbbKX4uw9lywalzkuKbyD20boaJeJfKAkXguQAzquZB1+n1cpeKO/2qkMQ+2M6iSIT+kM0qPZrS6xJ5ENrjxlDqIuDLlw/XZqRUyEdm9SKDYycq9Imw5aOFI2uTyrjowBlTRNTqbclo6NOak4YQ5zGzk0Rqq2tQKXgamEhmF5JwACQo1DsJapK7ihJC+blSIlkDSvrmUivgjJmF8GdFzgSumek60MRwqqs9t9PdmV/p3rzm+nlcstpwh3s7DVMTLMGkXXqdr2CJAQXFb0QRag6chURAPRSA4N6Z8bm45LURwJq5mHetm9tbxQHoWwV1/SIjQ2wgAeTZNog1jCk/4LSdDCTrAx1/0MVjVUOIY+hlH4UvZDS61CSeDEZUH4HTttz+Zbf01byu63LyC6mg7WwTMRHGc8T36c/XPrKzgSVkLqeDOZVani9hakUvcHT5EyMYXUZmECQ7GTHRB4Ttf2wREPSIRX1FdOnm10+JUb9YqRkVHbvb/ye+1l1DNLcmBNGOLyQb9M=
  on:
    tags: true
    branch: master

